title: Manoel Reviews
email: manoel910@usp.br
description: >- # this means to ignore newlines until "baseurl: Este é um canteiro vivo. A direção do projeto é dinamica, mas a construcao somente crescente. Sinta-se a vontade para explorar e volte sempre."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manoel.reviews" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

baseurl:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
